group_id: 0
data:
  dataset_sources:
    - path: "allenai/c4"
      name: "en"
      weight: 0.5
      text_column: "text"
    - path: "nvidia/Nemotron-CC-Math-v1"
      name: "4plus"
      weight: 0.5
      text_column: "text"
  per_device_train_batch_size: 1
  batch_size: 4
  sequence_length: 4096
  world_size: 1 # TODO: approximately how many miners are out there
  rank: 0 # TODO: based on your uid
  dataset_class: "expert_groups.exp_math.dataset:StreamingTorchDataset"